### ISSUE TITLE
Feature: Add a RequestHost token

### ISSUE THREAD

**Issue by nickchomey** [the-ccsn/traefik-plugin-rewritebody#5]
**Is your feature request related to a problem? Please describe.**
My webapp cannot use relative paths for static assets, so I am using this great plugin to rewrite urls for static assets in the html response body. I can generally just remove the scheme://host, leaving just the relative path, however it would be useful to be able to simply replace the hostname in the absolute path.

e.g. `abc.com` is the site, accessed via `dev.xyz.com`. If `abc.com/abc.css` is in the body, i want it to become `dev.xyz.com/abc.css` (rather than just `/abc.css`)

**Describe the solution you'd like**
I'm also using this plugin to rewrite headers, and it has a mechanism that allows you to use the RequestHost as a token in the replacement. https://github.com/jamesmcroft/traefik-plugin-rewrite-response-headers

e.g. something like
```
regex: "(https?://)abc\.com(/.*)?"
replacement: "$1{RequestHost}$2"
```

I've been poking around in the code of this plugin, but I'm new to traefik and Go, so not quite sure how to make something like this happen. 

Is there any chance you could add a mechanism like this? Or point me in the right direction of creating a PR myself?

Thanks!

**Comment by nickchomey** [comment]
Here is what they specifically did to add this functionality 

https://github.com/jamesmcroft/traefik-plugin-rewrite-response-headers/compare/29974b8..d7f9433

**Comment by isning** [comment]
hmm, that isn't what should this plugin do because this is a plugin for rewriting only response body
I believe what you need is just create a middleware chain...
like following:
user request response -> htransformation(rewrite header) -> upstream response -> rewritebody -> user side
For k8s configuration:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: abc-reroute
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`^.+\.abc\.com$`)
      kind: Rule
      middlewares:
      - name: host-transformation
      - name: response-headers-rewrite
      - name: response-rewrite
      services:
      - name: traefik
        port: web
```
(Actually, I'm doing similiar thing like you, and this is what I'm using for rewrite headers: https://github.com/tomMoulard/htransformation/commit/d3b793ac8a66d7d9164f8f3989a5834e4926a6af)
